apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceQuota.name }}
  namespace: {{ .Values.resourceQuota.namespace| default .Release.Namespace }}
spec:
  hard:
{{- range $key, $value := .Values.resourceQuota.hard }}
    {{ $key }}: "{{ $value }}"
{{- end }}