apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.deployment.containerPort }}
  type: LoadBalancer
