apiVersion: v2
name: cluster-issuer
description: A Helm chart for deploying cluster-issuer
type: application
version: 0.1.24
appVersion: 1.16.4
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.svg
