deployment:
  replicaCount: 1
  maxSurge: 1
  maxUnavailable: 0
  imagePullPolicy: Always
  containerPort: 80
  imagePullSecrets: []
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  restartPolicy: Always
  envFrom: []

ingress:
  path: /
  pathType: Prefix
