# Cluster Issuer configuration
clusterIssuer:
  name: letsencrypt-issuer
  acme:
    email: your-email@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: your-email@example.com
          apiKeySecretRef:
            name: cloudflare-api-token-secret
            key: api-token
