name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v4
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Update version
      run: |
        for chart in $(ls -d charts/*); do
          current_version=$(helm show chart $chart | grep "^version:" | awk '{print $2}')
          IFS='.' read -r -a version_parts <<< "$current_version"
          last_index=$(( ${#version_parts[@]} - 1 ))
          version_parts[$last_index]=$(( ${version_parts[$last_index]} + 1 ))
          new_version=$(IFS='.'; echo "${version_parts[*]}")
          yq e ".version = \"$new_version\"" -i $chart/Chart.yaml;
          git add $chart/Chart.yaml;
        done
        git commit -m "Update version for next release"
        git push
